name        = "FR-Go"
name8       = "frgo"
locale      = "fr"
variant     = "Kawa"
author      = "Kawamashi"
description = "French Ergo"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "3.0.5"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ Ç   ┃ 1   │ «   │ »   │ 4   │ 5   ┃ 6 ‚ │ 7 ‘ │ 8 ’ │ 9   │ …   ┃ /   ┆ *   ┆
┆     ┃   ß │ 2 ∞ │ 3 ñ │   § │   ¶ ┃   ™ │   £ │   ° │   © │ 0 € ┃   ÷ ┆   × ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ X   │ !   │ É   │ P   │ B   ┃ F „ │ M “ │ L ” │ ? ¿ │ : ¡ ┃ ≠ ≠ ┆ +   ┆
·     ┃   ô │ , â │   î │   û │   µ ┃   " │   « │   » │ ’ • │ . · ┃ = ≈ ┆   ± ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ O   │ A   │ I ‑ │ T   │ G   ┃ V   │ S   │ N   │ R   │ U   ┃ -   ┆ ? ¿ ┆
·     ┃   ê │   à │   - │   ù │  *µ ┃   ß │   ( │   ) │   ñ │   … ┃   − ┆ ' • ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ E   ┃ Q   │ Z   │ Y   │ D — │ J   ┃ K   │ C   │ H   │ W _ │ ;   ┃           ·
┆   è ┃   œ │   æ │   ï │   – │   @ ┃   € │   ç │  *¨ │   _ │**   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃   à ┆   ê ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ¬ │   ≠ │  *¤ │   ‰ ┃  *˚ │   ≤ │   ≥ │     │  *ˇ ┃     ┆     ┆
·     ┃   ^ │   ! │   = │   $ │   % ┃   # │   < │   > │   ? │   : ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   × │   ± │  *¯ │   ÷ │  */ ┃  *` │  *´ │     │  *˘ │     ┃     ┆     ┆
·     ┃   * │   + │   - │   / │   \ ┃   ` │   ( │   ) │   ; │   ' ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │   ¦ │     │  *” │     ┃     │  *¸ │  *, │  *˛ │     ┃           ·
┆   _ ┃   ~ │   | │   & │   " │   @ ┃     │   { │   } │   [ │   ] ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u002d"  # HYPHEN-MINUS
1dk_shift   = "\u002d"  # HYPHEN-MINUS
