name        = "FR-Go"
name8       = "frgo"
locale      = "fr"
variant     = "Kawa"
author      = "Kawamashi"
description = "French Ergo"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "3.0.2"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ Ç   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6 ‚ │ 7 ‘ │ 8 ’ │ 9   │ 0   ┃ /   ┆ *   ┆
┆     ┃   ß │   ∞ │   ñ │   § │   ¶ ┃   ™ │   £ │   ° │   © │   € ┃   ÷ ┆   × ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ X   │ !   │ É   │ P   │ B   ┃ F „ │ M “ │ L ” │ ? ¿ │ : ¡ ┃ ≠ ≠ ┆ +   ┆
·     ┃   ô │ , â │   î │   û │   µ ┃   " │   « │   » │ ’ • │ . · ┃ = ≈ ┆   ± ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ O   │ A   │ I ‑ │ T — │ G   ┃ V   │ S   │ N   │ R   │ U   ┃ -   ┆ ? ¿ ┆
·     ┃   ê │   à │   - │   – │  *µ ┃   ß │   ( │   ) │   ñ │   … ┃   − ┆ ' • ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ E   ┃ Q   │ Z   │ Y   │ D   │ J   ┃ K   │ C   │ H   │ W _ │ ;   ┃           ·
┆   è ┃   œ │   æ │   ï │   ù │   @ ┃   € │   ç │  *¨ │   _ │**   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆   à ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ¬ │   ≠ │  *¤ │   ‰ ┃  *˚ │  *˘ │     │     │  *ˇ ┃     ┆     ┆
·     ┃   ^ │   ! │   = │   $ │   % ┃   # │   ; │   ' │   ? │   : ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   × │   ± │  *¯ │   ÷ │  */ ┃  *` │  *´ │     │   ≤ │   ≥ ┃     ┆     ┆
·     ┃   * │   + │   - │   / │   \ ┃   ` │   ( │   ) │   < │   > ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │   ¦ │     │  *” │     ┃     │  *¸ │  *, │  *˛ │     ┃           ·
┆   _ ┃   ~ │   | │   & │   " │   @ ┃     │   { │   } │   [ │   ] ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION marker
